version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: lumina-vector-db
    ports:
      - "6333:6333" # API 端口
      - "6334:6334" # gRPC 端口
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: always